package dev.streamx.util;

import info.magnolia.rendering.engine.AppendableOnlyOutputProvider;
import info.magnolia.rendering.engine.RenderException;
import info.magnolia.rendering.engine.RenderingEngine;
import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.io.OutputStream;
import java.io.OutputStreamWriter;
import java.io.Writer;
import javax.jcr.Node;
import lombok.AccessLevel;
import lombok.NoArgsConstructor;
import org.jsoup.Jsoup;
import org.jsoup.nodes.Document;
import org.jsoup.nodes.Element;
import org.jsoup.select.Elements;

@NoArgsConstructor(access = AccessLevel.PRIVATE)
public final class HtmlUtil {

  /**
   * A static method which will render the HTML of a page node. It will also remove the unnecessary
   * instance value from the links, anchor elements and images generated by the default behaviour
   * of the RenderingEngine of Magnolia.
   *
   * @param renderingEngine engine that will handle the rendering
   * @param node page node that will be rendered
   * @return rendered page HTML as String
   */
  public static String generatePageHtml(RenderingEngine renderingEngine, Node node) throws RenderException, IOException {
    OutputStream outputStream = new ByteArrayOutputStream();
    OutputStreamWriter writer = new OutputStreamWriter(outputStream);
    AppendableOnlyOutputProvider appendable = new AppendableOnlyOutputProvider(writer);
    renderingEngine.render(node, appendable);
    ((Writer) appendable.getAppendable()).flush();
    String rawHtml = outputStream.toString();
    return removeInstanceFromPaths(rawHtml);
  }

  private static String removeInstanceFromPaths(String pageHtml) {
    Document document = Jsoup.parse(pageHtml);
    Elements links = document.select("a[href], link[href]");
    for (Element link : links) {
      String newHref = link.attr("href").replace("/magnoliaAuthor", "");
      link.attr("href", newHref);
    }
    Elements images = document.select("img[src]");
    for (Element image : images) {
      String newSrc = image.attr("src").replace("/magnoliaAuthor", "");
      image.attr("src", newSrc);
    }
    return document.outerHtml();
  }

}
